export enum PhotosSortType {
  DATE_INCREASE = "DATE_INCREASE",
  DATE_DECREASE = "DATE_DECREASE",
  VIEWS_INCREASE = "VIEWS_INCREASE",
  VIEWS_DECREASE = "VIEWS_DECREASE",
  HEARTS_INCREASE = "HEARTS_INCREASE",
  HEARTS_DECREASE = "HEARTS_DECREASE",
}
