#DOCKERFILE pozwala dolozyc cos do budujacego sie kontenera/kontenerow w docker-compose'a (rozszerza go) docker-compose sam w sobie ma byc jak najlzejszy z
#najabrdziej podstawowa i uniwersalna konfiguracja, a wszystko co jest bardziej specyficzne ma byc w dockerfile'u
#potem trzeba podlinkowac dockerfilea odpowiednio w composie jak sie chce

FROM alpine:latest