global:
  scrape_interval: 5s        # How frequently to scrape targets
  scrape_timeout: 2s         # Timeout before considering the scrape failed
  evaluation_interval: 1m    # How frequently to evaluate rules

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - '192.168.0.159:8080'  # Update this IP address to match your local setup
