export enum FavoriteSpotsListType {
  ALL = "ALL",
  FAVORITE = "FAVORITE",
  PLAN_TO_VISIT = "PLAN_TO_VISIT",
  VISITED_LIED_IT = "VISITED_LIED_IT",
  VISITED_NOT_LIED_IT = "VISITED_NOT_LIED_IT",
  COMMENTED_BY_YOU = "COMMENTED_BY_YOU",
}
