export enum FavoriteSpotsListType {
    ALL = "ALL",
    FAVORITE = "FAVORITE",
    PLAN_TO_VISIT = "PLAN_TO_VISIT",
    VISITED_LIKED_IT = "VISITED_LIKED_IT",
    VISITED_NOT_LIKED_IT = "VISITED_NOT_LIKED_IT",
    COMMENTED_BY_YOU = "COMMENTED_BY_YOU",
}
