name: React CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master, develop ]
  merge_group:
    branches: [ master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: venus
        run: npm install

      - name: Run tests
        working-directory: venus
        run: npm test

      - name: Run E2E tests
        working-directory: venus
        run: npm cypress:run
