name: React CI

on:
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
    paths:
      - 'venus/**'
  pull_request:
    types:
      - opened
    branches:
      - master
      - develop
  merge_group:
    branches: [ master, develop ]

jobs:
    test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: venus

      - name: Run tests
        working-directory: venus
        run: npm test
